### PR TITLE
Fix arm64 behavior in 0.27.0+

### LINKED ISSUE #26: The latest script installs 0.27.0 amd64 version on Mac M1
Maybe it's a regression since the `0.26.7` `arm64` version can be installed on Mac M1 correctly.

```bash
$ sw_vers
ProductName:		macOS
ProductVersion:		13.2
BuildVersion:		22D49

$ uname -a
Darwin **** 22.3.0 Darwin Kernel Version 22.3.0: Thu Jan  5 20:49:43 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T8103 arm64

$ asdf install k9s 0.27.0
[2023-01-30 00:47:34] INFO: Downloading [k9s] from 
https://github.com/derailed/k9s/releases/download/v0.27.0/k9s_darwin_amd64.tar.gz to 
/var/folders/gd/****/T/asdf_XXXXXXXX.jdhdXIxN/sub/k9s_darwin_amd64.tar.gz (install_tool)
[2023-01-30 00:47:43] INFO: Creating bin directory [/Users/****/.asdf/installs/k9s/0.27.0/bin] (install_tool)
[2023-01-30 00:47:43] INFO: Cleaning previous binaries if any (install_tool)
[2023-01-30 00:47:43] INFO: Extracting archive (install_tool)
[2023-01-30 00:47:43] INFO: Copying binaries (install_tool)
```

### PR DESCRIPTION
**Pull request by libfitz**
Reverts some of the changes made in #25.
Should fix #26.

### CODE REVIEW

**Review by canterberry — APPROVED** [review]
:+1: LGTM. I'm not familiar enough with the install script here to have 100% confidence it doesn't break anything, but the changeset does involve the exact problem I'm seeing when managing k9s 0.27.0+, where the release naming conventions have changed from `x86_64` to `amd64`.

**Comment by canterberry** [comment]
For reference, here's the breaking k9s PR: https://github.com/derailed/k9s/pull/1910

**Comment by affectiosus** [comment]
@looztra can this be merged please?

**Comment by looztra** [comment]
I am so late on this one.

**Pull request merged**
